version: "3.4"
services:
  web:
    build: ./web
    command: yarn start
    environment:
      - PORT=8000
    volumes:
      - ./web:/app
      - node-modules:/app/node_modules
    ports:
      - "8000:8000"
volumes:
  node-modules:
